### ISSUE TITLE
[common/docs] 0. 일정 관리, 요구사항 정리

### ISSUE THREAD

**Issue by donggi-lee-bit** [donggi-lee-bit/comma#1]
# 📝 구현 목록

## 일정 관리

- 프로젝트 총 기간
- 적용할 기술
- 체크 포인트 설정

## 요구 사항 정리

- 시나리오를 통해 구현할 기능 설정
- 기술 스택 선정
- 기술 스택을 선정함에 있어 의사 결정 문서 작성

## References

[성공적인 사이드 프로젝트를 위한 네 가지 팁](https://brunch.co.kr/@s0ojin/36)

**Comment by donggi-lee-bit** [comment]
[일정 관리](https://victorious-lint-a8e.notion.site/ece105f7abb1439196c922212f282034)
[요구 사항 정리](https://victorious-lint-a8e.notion.site/API-5f000c2f615f48739117bca00dbace2c)

**Comment by ku-kim** [comment]
화이팅입니다 @donggi-lee-bit 🥳
